//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidApp.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CovidApp.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyone can get COVID-19, and most infections are usually mild, especially in children and young adults. But if you aren&apos;t in an area where COVID-19 is spreading, haven&apos;t traveled from an area where it&apos;s spreading, and haven&apos;t been in contact with someone who has it, your risk of infection is low..
        /// </summary>
        internal static string Anyone_can_get_COVID_19__and_most_infections_are_usually_mild__especially_in_children_and_young_adults__But_if_you_aren_t_in_an_area_where_COVID_19_is_spreading__haven_t_traveled_from_an_area_where_it_s_spreading__and_haven_t_been_in_contact_with_someone_who_has_it__your_risk_of_infection_is_lowLabel {
            get {
                return ResourceManager.GetString(@"Anyone can get COVID-19, and most infections are usually mild, especially in children and young adults. But if you aren't in an area where COVID-19 is spreading, haven't traveled from an area where it's spreading, and haven't been in contact with someone who has it, your risk of infection is lowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App icon is provided by icons8.com.
        /// </summary>
        internal static string App_icon_is_provided_by_icons8_comLabel {
            get {
                return ResourceManager.GetString("App icon is provided by icons8.comLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App&apos;s Version.
        /// </summary>
        internal static string App_s_VersionLabel {
            get {
                return ResourceManager.GetString("App\'s VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid close contact with people who are sick, maintain 3 feet/6 meters away from other people..
        /// </summary>
        internal static string Avoid_close_contact_with_people_who_are_sick__maintain_3_feet_6_meters_away_from_other_peopleLabel {
            get {
                return ResourceManager.GetString("Avoid close contact with people who are sick, maintain 3 feet/6 meters away from " +
                        "other peopleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid close contact!!.
        /// </summary>
        internal static string Avoid_close_contactLabel {
            get {
                return ResourceManager.GetString("Avoid close contactLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid touching eyes, nose and mouth!!.
        /// </summary>
        internal static string Avoid_touching_eyes__nose_and_mouthLabel {
            get {
                return ResourceManager.GetString("Avoid touching eyes, nose and mouthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluish lips or face.
        /// </summary>
        internal static string Bluish_lips_or_faceLabel {
            get {
                return ResourceManager.GetString("Bluish lips or faceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t wake up fully.
        /// </summary>
        internal static string Can_t_wake_up_fullyLabel {
            get {
                return ResourceManager.GetString("Can\'t wake up fullyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed:.
        /// </summary>
        internal static string ConfirmedDisplayLabelInGeneral {
            get {
                return ResourceManager.GetString("ConfirmedDisplayLabelInGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coronavirus Risk Factors.
        /// </summary>
        internal static string Coronavirus_Risk_FactorsLabel {
            get {
                return ResourceManager.GetString("Coronavirus Risk FactorsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coronavirus.
        /// </summary>
        internal static string CoronavirusLabel {
            get {
                return ResourceManager.GetString("CoronavirusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaths:.
        /// </summary>
        internal static string DeathDisplayLabelInGeneral {
            get {
                return ResourceManager.GetString("DeathDisplayLabelInGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed in Xamarin.Forms, one of the best software applications for developing cross-platform Mobile Apps!!.
        /// </summary>
        internal static string Developed_in_Xamarin_Forms__one_of_the_best_software_applications_for_developing_cross_platform_Mobile_AppsLabel {
            get {
                return ResourceManager.GetString("Developed in Xamarin.Forms, one of the best software applications for developing " +
                        "cross-platform Mobile AppsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer.
        /// </summary>
        internal static string DeveloperLabel {
            get {
                return ResourceManager.GetString("DeveloperLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabetes.
        /// </summary>
        internal static string DiabetesLabel {
            get {
                return ResourceManager.GetString("DiabetesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry Cough.
        /// </summary>
        internal static string DryCoughLabel {
            get {
                return ResourceManager.GetString("DryCoughLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early Symptoms include:.
        /// </summary>
        internal static string EarlySymptomsIncludeLabel {
            get {
                return ResourceManager.GetString("EarlySymptomsIncludeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatigue.
        /// </summary>
        internal static string FatigueLabel {
            get {
                return ResourceManager.GetString("FatigueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fever.
        /// </summary>
        internal static string FeverLabel {
            get {
                return ResourceManager.GetString("FeverLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find specific country....
        /// </summary>
        internal static string Find_specific_countryLabel {
            get {
                return ResourceManager.GetString("Find specific countryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A coronavirus is a kind of common virus that causes an infection in your nose, sinuses, or upper throat. Most coronaviruses aren&apos;t dangerous. COVID-19 is a disease that can cause what doctors call a respiratory tract infection. It can affect your upper respiratory tract (sinuses, nose, and throat) or lower respiratory tract (windpipe and lungs). It&apos;s caused by a coronavirus named SARS-CoV-2..
        /// </summary>
        internal static string GeneralCoronavirusLabel {
            get {
                return ResourceManager.GetString("GeneralCoronavirusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands touch many surfaces and can pick up viruses. Once contaminated, hands can transfer the virus to your eyes, nose or mouth..
        /// </summary>
        internal static string Hands_touch_many_surfaces_and_can_pick_up_viruses__Once_contaminated__hands_can_transfer_the_virus_to_your_eyes__nose_or_mouthLabel {
            get {
                return ResourceManager.GetString("Hands touch many surfaces and can pick up viruses. Once contaminated, hands can t" +
                        "ransfer the virus to your eyes, nose or mouthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harsh Mathur.
        /// </summary>
        internal static string Harsh_MathurLabel {
            get {
                return ResourceManager.GetString("Harsh MathurLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart, lung, or liver disease.
        /// </summary>
        internal static string Heart__lung__or_liver_diseaseLabel {
            get {
                return ResourceManager.GetString("Heart, lung, or liver diseaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have fever, cough and difficulty breathing, seek medical care early!!.
        /// </summary>
        internal static string If_you_have_fever__cough_and_difficulty_breathing__seek_medical_care_earlyLabel {
            get {
                return ResourceManager.GetString("If you have fever, cough and difficulty breathing, seek medical care earlyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In About Page, the Xamarin animation  is provided by LottieFilez in LottiesFiles.com.
        /// </summary>
        internal static string In_About_Page__the_Xamarin_animation__is_provided_by_LottieFilez_in_LottiesFiles_comLabel {
            get {
                return ResourceManager.GetString("In About Page, the Xamarin animation  is provided by LottieFilez in LottiesFiles." +
                        "comLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Information Page, the coronavirus animation is provided by LottiesFiles in LottiesFiles.com.
        /// </summary>
        internal static string In_Information_Page__the_coronavirus_animation_is_provided_by_LottiesFiles_in_LottiesFiles_comLabel {
            get {
                return ResourceManager.GetString("In Information Page, the coronavirus animation is provided by LottiesFiles in Lot" +
                        "tiesFiles.comLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Information Page, the information is written by Michael W. Smith, MD in webmd.com on April 24, 2020..
        /// </summary>
        internal static string In_Information_Page__the_information_is_written_by_Michael_W__Smith__MD_in_webmd_com_on_April_24__2020Label {
            get {
                return ResourceManager.GetString("In Information Page, the information is written by Michael W. Smith, MD in webmd." +
                        "com on April 24, 2020Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Information Page, the lungs animation is provided by Rohan Mahindrakar in LottiesFiles.com.
        /// </summary>
        internal static string In_Information_Page__the_lungs_animation_is_provided_by_Rohan_Mahindrakar_in_LottiesFiles_comLabel {
            get {
                return ResourceManager.GetString("In Information Page, the lungs animation is provided by Rohan Mahindrakar in Lott" +
                        "iesFiles.comLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Information Page, the microchart data is powered by Gramzivi in Rapid API website.
        /// </summary>
        internal static string In_Information_Page__the_microchart_data_is_powered_by_Gramzivi_in_Rapid_API_websiteLabel {
            get {
                return ResourceManager.GetString("In Information Page, the microchart data is powered by Gramzivi in Rapid API webs" +
                        "iteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In News Page, the news data is powered by Bing News Search in Rapid API website.
        /// </summary>
        internal static string In_News_Page__the_news_data_is_powered_by_Bing_News_Search_in_Rapid_API_websiteLabel {
            get {
                return ResourceManager.GetString("In News Page, the news data is powered by Bing News Search in Rapid API websiteLa" +
                        "bel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Statistics Page, the coronavirus data in all countries is powered by Gramzivi in Rapid API website.
        /// </summary>
        internal static string In_Statistics_Page__the_coronavirus_data_in_all_countries_is_powered_by_Gramzivi_in_Rapid_API_websiteLabel {
            get {
                return ResourceManager.GetString("In Statistics Page, the coronavirus data in all countries is powered by Gramzivi " +
                        "in Rapid API websiteLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Survival Guide Page, the Avoid Close Contact animation is provided by Md Najmul Islam Shakil in LottiesFiles.com.
        /// </summary>
        internal static string In_Survival_Guide_Page__the_Avoid_Close_Contact_animation_is_provided_by_Md_Najmul_Islam_Shakil_in_LottiesFiles_comLabel {
            get {
                return ResourceManager.GetString("In Survival Guide Page, the Avoid Close Contact animation is provided by Md Najmu" +
                        "l Islam Shakil in LottiesFiles.comLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Survival Guide Page, the Avoid touching your eyes, nose, face animation is provided by Wesley Guirra in LottiesFiles.com.
        /// </summary>
        internal static string In_Survival_Guide_Page__the_Avoid_touching_your_eyes__nose__face_animation_is_provided_by_Wesley_Guirra_in_LottiesFiles_comLabel {
            get {
                return ResourceManager.GetString("In Survival Guide Page, the Avoid touching your eyes, nose, face animation is pro" +
                        "vided by Wesley Guirra in LottiesFiles.comLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Survival Guide Page, the Seek Medical care animation is provided by Sarpreet Kaylan in LottiesFiles.com.
        /// </summary>
        internal static string In_Survival_Guide_Page__the_Seek_Medical_care_animation_is_provided_by_Sarpreet_Kaylan_in_LottiesFiles_comLabel {
            get {
                return ResourceManager.GetString("In Survival Guide Page, the Seek Medical care animation is provided by Sarpreet K" +
                        "aylan in LottiesFiles.comLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Survival Guide Page, the Try to stay home animation is provided by David Probst Jr in LottiesFiles.com.
        /// </summary>
        internal static string In_Survival_Guide_Page__the_Try_to_stay_home_animation_is_provided_by_David_Probst_Jr_in_LottiesFiles_comLabel {
            get {
                return ResourceManager.GetString("In Survival Guide Page, the Try to stay home animation is provided by David Probs" +
                        "t Jr in LottiesFiles.comLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Survival Guide Page, the Wash Your Hands animation is provided by Rajeesh VK in LottiesFiles.com.
        /// </summary>
        internal static string In_Survival_Guide_Page__the_Wash_Your_Hands_animation_is_provided_by_Rajeesh_VK_in_LottiesFiles_comLabel {
            get {
                return ResourceManager.GetString("In Survival Guide Page, the Wash Your Hands animation is provided by Rajeesh VK i" +
                        "n LottiesFiles.comLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kidney disease that needs dialysis.
        /// </summary>
        internal static string Kidney_disease_that_needs_dialysisLabel {
            get {
                return ResourceManager.GetString("Kidney disease that needs dialysisLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate to severe asthma.
        /// </summary>
        internal static string Moderate_to_severe_asthmaLabel {
            get {
                return ResourceManager.GetString("Moderate to severe asthmaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New confusion.
        /// </summary>
        internal static string New_confusionLabel {
            get {
                return ResourceManager.GetString("New confusionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongoing chest pain or pressure.
        /// </summary>
        internal static string Ongoing_chest_pain_or_pressureLabel {
            get {
                return ResourceManager.GetString("Ongoing chest pain or pressureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People over 65 are most likely to get a serious illness, as are those who live in nursing homes or long-term care facilities, who have weakened immune systems, or who have medical conditions including:.
        /// </summary>
        internal static string People_over_65_are_most_likely_to_get_a_serious_illness__as_are_those_who_live_in_nursing_homes_or_long_term_care_facilities__who_have_weakened_immune_systems__or_who_have_medical_conditions_includingLabel {
            get {
                return ResourceManager.GetString("People over 65 are most likely to get a serious illness, as are those who live in" +
                        " nursing homes or long-term care facilities, who have weakened immune systems, o" +
                        "r who have medical conditions includingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovered:.
        /// </summary>
        internal static string RecoveredDisplayLabelInGeneral {
            get {
                return ResourceManager.GetString("RecoveredDisplayLabelInGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regularly and thoroughly clean your hands with an alcohol-based hand rub or wash them with soap and water..
        /// </summary>
        internal static string Regularly_and_thoroughly_clean_your_hands_with_an_alcohol_based_hand_rub_or_wash_them_with_soap_and_waterLabel {
            get {
                return ResourceManager.GetString("Regularly and thoroughly clean your hands with an alcohol-based hand rub or wash " +
                        "them with soap and waterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe obesity.
        /// </summary>
        internal static string Severe_obesityLabel {
            get {
                return ResourceManager.GetString("Severe obesityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay home if you feel unwell. If you have a fever, cough and difficulty breathing, seek medical attention and call in advance..
        /// </summary>
        internal static string Stay_home_if_you_feel_unwell__If_you_have_a_fever__cough_and_difficulty_breathing__seek_medical_attention_and_call_in_advanceLabel {
            get {
                return ResourceManager.GetString("Stay home if you feel unwell. If you have a fever, cough and difficulty breathing" +
                        ", seek medical attention and call in advanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staying at home reduces the spread of coronavirus and reduces the risk of getting infected as well as spread to other people..
        /// </summary>
        internal static string Staying_at_home_reduces_the_spread_of_coronavirus_and_reduces_the_risk_of_getting_infected_as_well_as_spread_to_other_peopleLabel {
            get {
                return ResourceManager.GetString("Staying at home reduces the spread of coronavirus and reduces the risk of getting" +
                        " infected as well as spread to other peopleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symptoms of COVID-19.
        /// </summary>
        internal static string SymptomsofCovidLabel {
            get {
                return ResourceManager.GetString("SymptomsofCovidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The virus can lead to pneumonia, respiratory failure, septic shock, and death. If you notice the following severe symptoms in yourself or a loved one, get medical help right away:.
        /// </summary>
        internal static string The_virus_can_lead_to_pneumonia__respiratory_failure__septic_shock__and_death__If_you_notice_the_following_severe_symptoms_in_yourself_or_a_loved_one__get_medical_help_right_awayLabel {
            get {
                return ResourceManager.GetString("The virus can lead to pneumonia, respiratory failure, septic shock, and death. If" +
                        " you notice the following severe symptoms in yourself or a loved one, get medica" +
                        "l help right awayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a page that I give credits to people that who have made their work and to respect their copyrights.
        /// </summary>
        internal static string This_is_a_page_that_I_give_credits_to_people_that_who_have_made_their_work_and_to_respect_their_copyrightsLabel {
            get {
                return ResourceManager.GetString("This is a page that I give credits to people that who have made their work and to" +
                        " respect their copyrightsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trouble breathing or shortness of breath.
        /// </summary>
        internal static string Trouble_breathing_or_shortness_of_breathLabel {
            get {
                return ResourceManager.GetString("Trouble breathing or shortness of breathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to stay home!!.
        /// </summary>
        internal static string Try_to_stay_homeLabel {
            get {
                return ResourceManager.GetString("Try to stay homeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wash your hands!!.
        /// </summary>
        internal static string Wash_your_handsLabel {
            get {
                return ResourceManager.GetString("Wash your handsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worldwide Statistics.
        /// </summary>
        internal static string Worldwide_StatisticsLabel {
            get {
                return ResourceManager.GetString("Worldwide StatisticsLabel", resourceCulture);
            }
        }
    }
}
